global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "track_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "main:25566",
            "audit-service:25567",
            "statistics-service:25568",
          ]
